### Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}

### Who am I
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Get all users with a given email
GET http://localhost:3000/auth?email=smith@gmai.com

### Get a user
GET http://localhost:3000/auth/3

### Update a user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "password": "smith123"
}

### Delete a user
DELETE http://localhost:3000/auth/1

# ### Set color
# GET http://localhost:3000/auth/colors/red

# ### Get color
# GET http://localhost:3000/auth/colors

